spring:
  application:
    name: SpringToDo
  data:
    redis:
      host: redis
      port: 6379
  datasource:
    url: jdbc:postgresql://postgres:5432/to_do_base
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: qwerty
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
server:
  port: 8080
