apiVersion: v1
kind: Pod
metadata:
  name: redis-pod
  labels:
    name: redis-pod
    type: backend
spec:
  containers:
    - name: redis
      image: redis:6.2-alpine
      ports:
        - containerPort: 6379