apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  labels:
    name: redis-deployment
    type: backend
spec:
  selector:
    matchLabels:
      name: redis-pod
      type: backend
  template:
    metadata:
      name: redis-pod
      labels:
        name: redis-pod
        type: backend
    spec:
      containers:
        - name: redis
          image: redis:6.2-alpine
          ports:
            - containerPort: 6379
