apiVersion: v1
kind: Pod
metadata:
  name: spring-pod
  labels:
    app: spring-pod
    type: backend
spec:
  containers:
    - name: spring
      image: vkontakte001/spring-to-do
      ports:
        - containerPort: 8080